
import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'jarvis-ui',
    title: 'Jarvis 全息界面',
    description: '受钢铁侠启发的沉浸式全息 UI 体验，展示了未来的 Web 交互设计。',
    url: 'https://gemini.bornforthis.cn/jarvis-holographic-ui/',
    githubUrl: 'https://github.com/AndersonHJB/jarvis-holographic-ui', // Replace with actual
    articleUrl: 'https://bornforthis.cn/column/Python-Programming-Course/P10-Share/Interesting-project/01-Gemini3-jarvis-holographic-ui.html', // Replace with actual
    // thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    thumbnailUrl: '/images/P01-贾维斯.png',
    tags: ['React', 'TypeScript', 'Three.js', 'React Three Fiber', 'MediaPipe', 'Tailwind CSS'],
    iconName: 'Cpu',
    status: 'live',
    featured: true,
  },
  {
    id: 'gemini-chat',
    title: 'Gemini 智能助手',
    description: '基于 Google Gemini API 构建的下一代对话式 AI 助手，支持多模态输入。',
    url: '#',
    githubUrl: 'https://github.com/AndersonHJB',
    tags: ['AI', 'Gemini API', 'Chat'],
    iconName: 'Sparkles',
    status: 'beta',
    thumbnailUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800',
  },
  // {
  //   id: 'vision-analyzer',
  //   title: '视觉分析实验室',
  //   description: '上传图片即可获得深度分析，利用最新的视觉识别模型识别物体与场景。',
  //   url: '#',
  //   articleUrl: 'https://bornforthis.cn',
  //   tags: ['Computer Vision', 'Analysis'],
  //   iconName: 'Eye',
  //   status: 'concept',
  // },
  // {
  //   id: 'infinite-canvas',
  //   title: '无限创意画板',
  //   description: '一个基于 WebGL 的无限缩放协作白板，支持实时多人绘图与思维导图构建。',
  //   url: '#',
  //   tags: ['WebGL', 'Collaboration', 'Canvas'],
  //   iconName: 'Palette',
  //   status: 'beta',
  //   thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800'
  // },
  // {
  //   id: 'crypto-dash',
  //   title: 'DeFi 聚合仪表盘',
  //   description: '实时追踪加密货币市场动态，集成 Web3 钱包连接与链上数据分析功能。',
  //   url: '#',
  //   tags: ['Web3', 'Blockchain', 'Data Viz'],
  //   iconName: 'LineChart',
  //   status: 'live',
  // },
  // {
  //   id: 'neo-rpg',
  //   title: 'CyberCity 2077',
  //   description: '运行在浏览器中的 3D 赛博朋克风格 RPG 漫游体验，使用 Three.js 构建。',
  //   url: '#',
  //   tags: ['Three.js', 'Game Dev', '3D'],
  //   iconName: 'Gamepad2',
  //   status: 'concept',
  //   thumbnailUrl: 'https://images.unsplash.com/photo-1614728853913-1e2211f9780f?auto=format&fit=crop&q=80&w=800'
  // },
  // {
  //   id: 'smart-home',
  //   title: 'IoT 智能中控',
  //   description: '跨平台的智能家居控制中心，支持 MQTT 协议与主流智能设备联动。',
  //   url: '#',
  //   tags: ['IoT', 'PWA', 'MQTT'],
  //   iconName: 'Wifi',
  //   status: 'maintenance',
  // },
  // {
  //   id: 'code-fusion',
  //   title: 'CodeFusion 在线 IDE',
  //   description: '支持多种语言的云端代码编辑器，具备实时协作与 AI 代码补全功能。',
  //   url: '#',
  //   tags: ['IDE', 'Monaco', 'WebSockets'],
  //   iconName: 'Code',
  //   status: 'beta',
  // },
  // {
  //   id: 'ai-melody',
  //   title: 'AI 旋律生成器',
  //   description: '输入情绪描述，AI 自动生成独特的 Lo-Fi 背景音乐，助你专注或放松。',
  //   url: '#',
  //   tags: ['Audio API', 'GenAI', 'Music'],
  //   iconName: 'Music',
  //   status: 'live',
  //   thumbnailUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&q=80&w=800'
  // },
  // {
  //   id: 'eco-tracker',
  //   title: '碳足迹追踪器',
  //   description: '可视化的个人碳排放计算器，提供环保生活建议与数据图表分析。',
  //   url: '#',
  //   tags: ['Sustainability', 'D3.js', 'Green'],
  //   iconName: 'Leaf',
  //   status: 'live',
  // },
  // {
  //   id: 'virtual-museum',
  //   title: '数字文物博物馆',
  //   description: '高精度扫描文物的线上 3D 展厅，支持 VR 模式沉浸式参观。',
  //   url: '#',
  //   tags: ['VR', 'WebXR', 'Culture'],
  //   iconName: 'Box',
  //   status: 'concept',
  // },
  // {
  //   id: 'security-shield',
  //   title: '漏洞扫描卫士',
  //   description: '针对 Web 应用的轻量级安全检测工具，自动识别常见的前端安全隐患。',
  //   url: '#',
  //   tags: ['Security', 'Scanner', 'Tools'],
  //   iconName: 'Shield',
  //   status: 'beta',
  // }
];
